language: perl
perl:
  - 5.16
  - 5.14
  - 5.12
  - 5.10
before_install:
  - cpanm -nq App::mymeta_requires
install:
  - mymeta-requires | cpanm -nq
  - cpanm -nq Devel::Cover::Report::Coveralls
script:
  - perl Makefile.PL && cover -test
after_success:
  - cover -report coveralls
